name: AlexWarehouse CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build Backend
        run: mvn clean install -DskipTests

      - name: Run Backend Tests
        run: mvn test

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('warehousefrontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install Dependencies
        working-directory: warehousefrontend
        run: npm install

      - name: Lint Frontend Code
        working-directory: warehousefrontend
        run: npm run lint

      - name: Build Frontend
        working-directory: warehousefrontend
        run: npm run build

      - name: Test Frontend
        working-directory: warehousefrontend
        run: npm test

  deploy:
    name: Deploy to Server
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy Backend
        run: |
          # Exempel på kommando för att distribuera backend
          scp -r AlexWarehouse/ användare@server:/sökväg/till/distribution/backend

      - name: Deploy Frontend
        run: |
          # Exempel på kommando för att distribuera frontend
          scp -r warehousefrontend/dist användare@server:/sökväg/till/distribution/frontend
