# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]  # or your main branch name
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Java JDK 17 for backend
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build Backend with Maven
        run: mvn -B package -f pom.xml  # Adjust the path as necessary

      - name: Run Backend Tests
        run: mvn -B test -f pom.xml  # Adjust the path as necessary

      # Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cache npm/yarn dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install Frontend Dependencies
        working-directory: warehousefrontend  # Adjust this directory if needed
        run: npm install

      - name: Build Frontend
        working-directory: warehousefrontend  # Adjust this directory if needed
        run: npm run build

      - name: Run Frontend Tests
        working-directory: warehousefrontend  # Adjust this directory if needed
        run: npm run test -- --watchAll=false

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy Application
        # Add your specific deployment steps here
        run: echo "Deploying the application..."
