# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Check out repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Java JDK 17 for backend
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Build and Test Backend with Maven
      - name: Build Backend with Maven
        run: mvn -B package

      - name: Run Backend Tests
        run: mvn -B test

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports

      # Set up Node.js for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Cache npm/yarn dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      # Install Frontend Dependencies
      - name: Install Frontend Dependencies
        working-directory: warehousefrontend  # Adjust this directory if needed
        run: npm install

      # Build Frontend
      - name: Build Frontend
        working-directory: warehousefrontend  # Adjust this directory if needed
        run: npm run build

      # Run Frontend Tests
      - name: Run Frontend Tests
        working-directory: warehousefrontend  # Adjust this directory if needed
        run: npm run lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Add specific deployment steps here
      - name: Deploy Application
        run: echo "Deploying the application..."
